name = "Navigator Hugo"
license = "CC BY 3.0"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = "Hugo port of the Themefisher’s Navigator Template"
homepage = "https://themefisher.com/hugo-themes/"
tags = ["tags"]
features = ['bootstrap4','responsive','multilingual']
min_version = "0.58.0"

[author]
  name = "Themefisher"
  homepage = "https://themefisher.com/"


